name: Build, Test and Publish

run-name: ${{ github.actor }} is running the build, test, and publish workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Verify pnpm installation
      - run: pnpm --version

      - name: Run build
        run: pnpm build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  # publish:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Install dependencies
  #       run: pnpm install

  #     - name: Build packages
  #       run: pnpm build

  #     - name: Authenticate with npm
  #       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc

  #     - name: Publish to npm
  #       run: pnpx nx run package:nx-release-publish --access=public
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
