name: Build, Test and Publish

run-name: ${{ github.actor }} is running the build, test, and publish workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Install dependencies
      -  run: pnpm install

      - name: Verify pnpm installation
      - run: pnpm --version

      - name: Run build
      - run: pnpm build
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Install dependencies
      - run: pnpm install

      - name: Run tests
      - run: pnpm test

 